### ISSUE TITLE
Latest version contains no code !!!

### ISSUE THREAD

**Issue by paulrostorp** [meetup/graphql-joda-types#53]
Latest version (2.2.20) contains no code, check `node_modules`
Probably forgot to run build before publishing

**Comment by chenrui333** [comment]
@paulrostorp thanks for raising this issue, the `2.2.20` was indeed a faulty release, can you try `2.2.22`(or whichever after 2.2.20).

**Comment by chenrui333** [comment]
Should be good now, closing the issue.
